require(Seurat)
require(dplyr)
require(Matrix)
require(magrittr)
library(scales)
library(ggplot2)
library(configr)
library(cowplot)
library(Hmisc)
library(RColorBrewer)
library(presto)
library(presto)
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(ComplexHeatmap)
library(circlize)

grid.col<-colorRampPalette(brewer.pal(9, "Set1"))(5)[1:5]
rds<-readRDS('/annoroad/data1/bioinfo/PROJECT/big_Commercial/Cooperation/B_TET/TET_PUBLIC/zhaoyue/project/B_TET_074/IPF_dbfree.rds')
Idents(rds)<-rds@meta.data$cell.type
markers <- FindAllMarkers(object = rds, group.by = 'cell.type',logfc.threshold = 0.25,test.use = "wilcox",min.pct = 0.1,p_val_adj=0.05)
top5 <- markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)
gene<-c('Chil3','Lyz2','Lpl','Ear2','Apoe','Fscn1','H2-EB1','Mgl2','H2-Ab1','Trbc2','Cd3e','Il7r','Igkc','Cd79a','Ighd','H2-DMb2','Mzb1','S100a8','S100a9','Retnlg','Il1b','Cxcl2','Ccl5','Nkg7','Klrb1c','Gzmb','Klrd1','Ncr1')
mat<-rds@assays$RNA@data
index<-match(gene,top5$gene)
mat = as.matrix(mat[top5$gene,])
base_mean = rowMeans(mat)
mat_scaled = t(apply(mat, 1, scale))
newd<-rds@meta.data[order(rds@meta.data$cell.type),]
colnames(mat_scaled)<-row.names(rds@meta.data)
mat_scaled = as.matrix(mat_scaled[,row.names(newd)])
mat_scaled = as.matrix(mat_scaled[top5$gene,])
pdf('IPF_heatmpa.pdf',h=10,w=10)
har = rowAnnotation(foo = anno_mark(at = index, labels = gene))
df=data.frame(gene=newd$cell.type)
hac =  HeatmapAnnotation(df = df, annotation_name_side = "right",col=list(gene=c('Mac' = "#66C2A5",'Neu'="#AB98C8",'DC'="#BDA37D",'B'="#A89BB0",'NK'="#DF8BC3",'T.NKT'="#E99073")))
ht_list = Heatmap(mat_scaled, name = "expression",  col = colorRamp2(c(-2, 0, 2), c("#11659A", "white", "#A61B29")),top_annotation = hac, show_column_names = FALSE,show_row_names = FALSE, row_title = NULL, show_row_dend = FALSE,right_annotation = har,cluster_rows = FALSE,cluster_columns = FALSE,row_gap = unit(0, "mm"), column_gap = unit(0, "mm"))
draw(ht_list)
dev.off()
