require(Seurat)
require(dplyr)
require(Matrix)
require(magrittr)
library(scales)
library(ggplot2)
library(configr)
library(cowplot)
library(Hmisc)
library(RColorBrewer)
library(presto)
library(presto)
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(ComplexHeatmap)
library(circlize)

mat<-read.table('draw_heatmap_figure7.xls',header=T,row.names=1)
mat_scaled = t(apply(mat, 1, scale))
#mat_scaled = as.matrix(mat_scaled[,c('Mac', 'Mac', 'DC', 'DC', 'T.NKT', 'T.NKT', 'B', 'B','Neu', 'Neu', 'NK', 'NK')])
gene<-c('APOE','C1QB','C1QA','CTSD','FN1','CCL17','MGL2','CLEC10A','HLA-DQA1','TMEM176B','CD3D','CD3G','CD3E','LCK','BCL11B','CD79A','CD79B','MS4A1','BANK1','VPREB3','S100A8','S100A9','IL1R2','CD14','IFITM2','CCL5','NKG7','GZMA','KLRB1','PRF1')
index<-match(gene,row.names(mat))
har = rowAnnotation(foo = anno_mark(at = index, labels = gene))
df=data.frame(sample=c('Mac', 'Mac', 'DC', 'DC', 'T.NKT', 'T.NKT', 'B', 'B','Neu', 'Neu', 'NK', 'NK'))
pdf('combine_marker.pdf',w=8,h=8)
hac =  HeatmapAnnotation(df = df, annotation_name_side = "right",col=list(sample=c('Mac' = "#6EBDA3",'DC'="#CD948D",'T.NKT'="#C490B5",'B'="#BAD15C",'Neu'='#EFCC6B','NK'='#B3B3B3')))

ht_list = Heatmap(mat_scaled, name = "expression",  col = colorRamp2(c(-1.5, 0, 1.5), c("#11659A", "white", "#A61B29")),top_annotation = hac, show_column_names = TRUE,show_row_names = FALSE, row_title = NULL, show_row_dend = FALSE,right_annotation = har,cluster_rows = FALSE,cluster_columns = FALSE,row_gap = unit(0, "mm"), column_gap = unit(0, "mm"))
draw(ht_list)
dev.off()
