require(Seurat)
require(dplyr)
require(Matrix)
require(magrittr)
library(scales)
library(ggplot2)
library(configr)
library(cowplot)
library(Hmisc)
library(RColorBrewer)
library(presto)
library(presto)
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(ComplexHeatmap)
library(circlize)

grid.col<-colorRampPalette(brewer.pal(9, "Set2"))(4)[1:4]
rds<-readRDS('/annoroad/data1/bioinfo/PROJECT/big_Commercial/Cooperation/B_TET/TET_PUBLIC/zhaoyue/project/B_TET_074/dimplot/Mac_without_UK.rds')
Idents(rds)<-rds@meta.data$cell.type
markers <- FindAllMarkers(object = rds, group.by = 'cell.type',logfc.threshold = 0.25,test.use = "wilcox",min.pct = 0.1,p_val_adj=0.05)
print (head(markers))
top5 <- markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)
write.table(top5,'macrophage.marker.xls',sep='\t',quote=F,col.names=T,row.names=F)
mat<-rds@assays$RNA@data
gene<-c('Ear1','Wfdc21','Chil3','Plet1','Ear2','Mmp12','Apoe','C1qc','C1qa','C1qb','Plac8','Ifitm3','Ifitm6','Ly6c2','Hp','Lst1','Pglyrp1','Plac8','Lst1','Hes1','Ifitm3','Ifitm6')
index<-match(gene,top5$gene)
mat = as.matrix(mat[top5$gene,])
base_mean = rowMeans(mat)
mat_scaled = t(apply(mat, 1, scale))
newd<-rds@meta.data[order(rds@meta.data$cell.type),]
colnames(mat_scaled)<-row.names(rds@meta.data)
mat_scaled = as.matrix(mat_scaled[,row.names(newd)])
mat_scaled = as.matrix(mat_scaled[top5$gene,])
pdf('Macrophage_heatmap.pdf',h=10,w=10)
har = rowAnnotation(foo = anno_mark(at = index, labels = gene))
df=data.frame(gene=newd$cell.type)
hac =  HeatmapAnnotation(df = df, annotation_name_side = "right",col=list(gene=c('AM' = "#66C2A5",'MonMac'="#AB98C8",'Mono'="#E1D83B",'IntMacs'="#B3B3B3")))
ht_list = Heatmap(mat_scaled, name = "expression",  col = colorRamp2(c(-2, 0, 2), c("#11659A", "white", "#A61B29")),top_annotation = hac, show_column_names = FALSE,show_row_names = FALSE, row_title = NULL, show_row_dend = FALSE,right_annotation = har,cluster_rows = FALSE,cluster_columns = FALSE,row_gap = unit(0, "mm"), column_gap = unit(0, "mm"))
draw(ht_list)
dev.off()
