require(Seurat)
require(dplyr)
require(Matrix)
require(magrittr)
library(scales)
library(ggplot2)
library(configr)
library(cowplot)
library(Hmisc)
library(RColorBrewer)
library(presto)
library(presto)
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(ComplexHeatmap)
library(circlize)

grid.col<-colorRampPalette(brewer.pal(9, "Set2"))(4)[1:4]
rds<-readRDS('AM.anno.rds')
Idents(rds)<-rds@meta.data$cell_type
markers <- FindAllMarkers(object = rds, group.by = 'cell_type',logfc.threshold = 0.25,test.use = "wilcox",min.pct = 0.1,p_val_adj=0.05)
top5 <- markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)
write.table(top5,'MonMac.marker.xls',sep='\t',quote=F,col.names=T,row.names=F)
mat<-rds@assays$RNA@data
gene<-c('Spp1','Fn1','H2-Aa','Trem2','Fabp1','Ear1','Krt79','Ear2','Stmn1','Pclaf','Top2a','Tubb5','Apoe','Junb','S100a4','Stmn1','Top2a','Tubb5','Pclaf','Kif23','Cenpf','Mcm3','Gmnn','E2f1','Isg15','Ifi211','Trim30a','Lgals3bp','Ly6e')
newd<-rds@meta.data[order(rds@meta.data$cell_type),]
index<-match(gene,top5$gene)
mat = as.matrix(mat[top5$gene,])
base_mean = rowMeans(mat)
mat_scaled = t(apply(mat, 1, scale))
colnames(mat_scaled)<-row.names(rds@meta.data)
mat_scaled = as.matrix(mat_scaled[,row.names(newd)])
mat_scaled = as.matrix(mat_scaled[top5$gene,])
pdf('heatmap.pdf',h=10,w=10)
har = rowAnnotation(foo = anno_mark(at = index, labels = gene))
df=data.frame(sample=newd$cell_type)
hac =  HeatmapAnnotation(df = df, annotation_name_side = "right",col=list(sample=c('Fabp5+Gpnmd+' = "#91D4C9",'Lung resident Ams'="#E9E8C0",'CCL17-producing'="#E69394",'Nr4a1+'="#81B0D3",'Fabp1-Car4-Krt79+Cidec+'='#E4C368','Isg15+Ly6e+'='#D9D9D9','Fabp1+Car4+Krt79+Cidec+'='#E2D2BB')))
ht_list = Heatmap(mat_scaled, name = "expression",  col = colorRamp2(c(-2, 0, 2), c("#11659A", "white", "#A61B29")),top_annotation = hac, show_column_names = TRUE,show_row_names = FALSE, row_title = NULL, show_row_dend = FALSE,right_annotation = har,cluster_rows = FALSE,cluster_columns = FALSE,row_gap = unit(0, "mm"), column_gap = unit(0, "mm"))
draw(ht_list)
dev.off()
