require(Seurat)
require(dplyr)
require(Matrix)
require(magrittr)
library(scales)
library(ggplot2)
library(configr)
library(cowplot)
library(Hmisc)
library(RColorBrewer)
library(presto)
library(presto)
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(ComplexHeatmap)
library(circlize)

grid.col<-colorRampPalette(brewer.pal(9, "Set2"))(4)[1:4]
rds<-readRDS('MonMac.anno.rds')
Idents(rds)<-rds@meta.data$cell_type
markers <- FindAllMarkers(object = rds, group.by = 'cell_type',logfc.threshold = 0.25,test.use = "wilcox",min.pct = 0.1,p_val_adj=0.05)
top5 <- markers %>% group_by(cluster) %>% top_n(n = 20, wt = avg_log2FC)
write.table(top5,'MonMac.marker.xls',sep='\t',quote=F,col.names=T,row.names=F)
mat<-rds@assays$RNA@data
gene<-c('Ccl4','Tnf','Egr1','H2-Ab1','Nfkbiz','Mmp12','Lpl','Mmp19','Spp1','Itgax','Fabp4','Pf4','Ccl7','Ccl2','Arg1','H2-Aa','C5ar1','Plac8','Chil3','Saa3','Ly6c2','F13a1','Ms4a4c','Napsa','Isg15','Cxcl10','Ifit3','Ms4a4c','Ly6a','Zbp1','Oasl2')
newd<-rds@meta.data[order(rds@meta.data$cell_type),]
index<-match(gene,top5$gene)
mat = as.matrix(mat[top5$gene,])
base_mean = rowMeans(mat)
mat_scaled = t(apply(mat, 1, scale))
colnames(mat_scaled)<-row.names(rds@meta.data)
mat_scaled = as.matrix(mat_scaled[,row.names(newd)])
mat_scaled = as.matrix(mat_scaled[top5$gene,])
pdf('heatmap.pdf',h=10,w=10)
har = rowAnnotation(foo = anno_mark(at = index, labels = gene))
df=data.frame(sample=newd$cell_type)
hac =  HeatmapAnnotation(df = df, annotation_name_side = "right",col=list(sample=c('Cx3cr1+'='#E41A1C','CD36+'='#47A265','C5ar1+'='#CB6651','F13a1+'='#E8D430','Isg15+Ly6a+'='#F781BF')))
ht_list = Heatmap(mat_scaled, name = "expression",  col = colorRamp2(c(-2, 0, 2), c("#11659A", "white", "#A61B29")),top_annotation = hac, show_column_names = FALSE,show_row_names = FALSE, row_title = NULL, show_row_dend = FALSE,right_annotation = har,cluster_rows = FALSE,cluster_columns = FALSE,row_gap = unit(0, "mm"), column_gap = unit(0, "mm"))
draw(ht_list)
dev.off()
